name: CD Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Render/Railway/Vercel
        run: |
          # Aquí va el comando para hacer el deployment a tu plataforma.
          # Asegúrate de configurar los secretos de GitHub para las credenciales necesarias.
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
